version: '2.1'
services:
  nibbles:
    build: 
      context: ./frontend
    volumes:
      - ./frontend/dist:/app/dist
      - ./frontend/bin:/app/bin
    ports:
      - "9090:9000"
  nibblejs:
    restart: always
    build: 
      context: ./nibbleappjs
    volumes:
      - ./nibbleappjs/server.js:/app/server.js
    ports:
      - "9091:9000"
    cpu_shares: 256
    mem_limit: 50M
  nibblets:
    restart: always
    build:
      context: ./nibbleAppTS
    volumes:
      - ./nibbleAppTS/dist:/app/dist
      - ./nibbleAppTS/bin:/app/bin
    ports:
      - "9092:9000"
    cpu_shares: 256
    mem_limit: 50M
  nibbleesteban:
    restart: always
    build:
      context: ./nibbleEsteban
    ports:
      - "9093:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    cpu_shares: 256
    mem_limit: 50M
  nibblenelson:
    restart: always
    build:
      context: ./nibbleNelson
    volumes:
      - ./nibbleNelson/dist:/app/dist
      - ./nibbleNelson/bin:/app/bin
    ports:
      - "9094:9000"
    cpu_shares: 256
    mem_limit: 50M
  nibblediegog:
    restart: always
    build:
      context: ./nibbleDiegoG
    volumes:
      - ./nibbleDiegoG/dist:/app/dist
      - ./nibbleDiegoG/bin:/app/bin
    ports:
      - "9095:9000"
    cpu_shares: 256
    mem_limit: 50M
